### PR TITLE
Quick fix

### PR DESCRIPTION
**Pull request by aikelb**
Hi! 
I was trying to use this module in the latest Foundry version but couldn't make it work.
I made a few changes based on other forks, and I'm not sure if the changes I did are correct, but seems to be working on my end. Hopefully it helps to make it work for other people without breaking anything!

(You probably wanna undo the modules.js file changes)

### CODE REVIEW

**Review by atiannicelli — APPROVED** [review]
I can confirm that this fixed issues for me as well

**Comment by CaosFR** [comment]
Hi and bigs thanks for your fork. Do you think you can solve this problem "https://github.com/syl3r86/gm-notes/issues/25" to ?

**Comment by aikelb** [comment]
> Hi and bigs thanks for your fork. Do you think you can solve this problem "#25" to ?

I'm not really an expert on Foundry modules to be honest ^^U. If I can reproduce I can try to fix it, but without errors to follow, it will be quite hard to be honest.

**Comment by CaosFR** [comment]
@aikelb Do you think you can try to update to v10, the master is dead ?

**Comment by aikelb** [comment]
@CaosFR I just tried updating it again. I hope it works!

**Comment by CaosFR** [comment]
Amazing ! Thanks , I will try that soon as I update to v10 :)

**Comment by CaosFR** [comment]
@aikelb I have update but I cannot use my old notes (create with the preview version). I still in v9, so I think is the problem

Console error : Cannot read not found. 

I have revert to syl3r86:master and it's ok. @bithir has create a update and a fix for v10. It's a really good work (https://github.com/syl3r86/gm-notes/pull/31). I think you can merge with him and use this master now.

**Comment by aikelb** [comment]
Then I'll close this. It doesn't make any sense if someone else already fixed it! 
Kudos to bithir!

**Pull request closed without merging**
